Feat: update

diff --git a/.github/workflows/performance-test-outband.yml b/.github/workflows/performance-test-outband.yml
--- a/.github/workflows/performance-test-outband.yml
+++ b/.github/workflows/performance-test-outband.yml
@@ -11,7 +11,7 @@ permissions:
 
 jobs:
   benchmark:
-    name: Run JavaScript benchmark example
+    name: Benchmark for extraction algorithm (outband)
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -32,13 +32,29 @@ jobs:
           npm run data &
           disown  # Run npm run data in the background and disown the process
 
-      - name: Wait for server
-        run: sleep 60  # Adjust the duration based on your needs
-
       - name: Verify server
-        run: |
-          curl http://localhost:8080/member-1.ttl
+        run:  |
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/member-1.ttl)
 
-      - name: Run performance test
-        run: |
-          node ./perf/perftest-outband.js | tee output.txt
+          if [ "$response_code" -eq 200 ]; then
+            echo "Server verification successful (HTTP 200)"
+          else
+            echo "Server verification failed with HTTP $response_code"
+            exit 1  # Exit the script with an error code
+          fi
+
+      - name: Store benchmark result
+        uses: benchmark-action/github-action-benchmark@v1
+        with:
+            name: Extraction algorithm Benchmark for inband data
+            tool: 'benchmarkjs'
+            output-file-path: output.txt
+            github-token: ${{ secrets.GITHUB_TOKEN }}
+            benchmark-data-dir-path: docs/
+            auto-push: true
+            # Show alert with commit comment on detecting possible performance regression
+            alert-threshold: '200%'
+            comment-on-alert: true
+            fail-on-alert: true
+            alert-comment-cc-users: '@xdxxxdx'
+  
